# SPDX-License-Identifier: Apache-2.0
"""Adapters for Thermodynamic Sampling Units (TSU)."""

from __future__ import annotations

from typing import Protocol, Tuple

import numpy as np

from .psi import PsiTopK, logq_for_ids

__all__ = ["TSUAdapter", "SimTSU"]


class TSUAdapter(Protocol):
    """Common interface shared by all TSU adapters."""

    def sample_categorical(
        self,
        psi: PsiTopK,
        batch_size: int,
        seed: int,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Draw categorical samples from ``F(ψ)``.

        Parameters
        ----------
        psi:
            ψ payload generated by the proposer.
        batch_size:
            Number of independent samples to draw.
        seed:
            Deterministic seed for the random number generator.

        Returns
        -------
        Tuple[np.ndarray, np.ndarray]
            Token identifiers of shape ``(batch_size,)`` and matching ``log q``.
        """


class SimTSU:
    """Software simulator that samples from ``F(ψ)``."""

    def __init__(self) -> None:
        """Instantiate the simulator."""

    def sample_categorical(
        self,
        psi: PsiTopK,
        batch_size: int,
        seed: int,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Sample using the ψ reference distribution.

        Parameters
        ----------
        psi:
            ψ payload specifying Top-K scores and tail mass.
        batch_size:
            Number of samples to produce.
        seed:
            Seed used to initialise the RNG (PCG64).

        Returns
        -------
        Tuple[np.ndarray, np.ndarray]
            Token identifiers and associated ``log q`` values.
        """

        if batch_size <= 0:
            raise ValueError("batch_size must be positive.")

        rng = np.random.Generator(np.random.PCG64(seed))

        all_ids = np.arange(int(psi.vocab_size), dtype=np.int32)
        logq_all = logq_for_ids(psi, all_ids)
        probs = np.exp(logq_all)

        tokens = rng.choice(all_ids, size=batch_size, replace=True, p=probs)

        log_q = logq_for_ids(psi, tokens.astype(np.int32))

        return tokens.astype(np.int32), log_q
